spring.application.name=Core
# Chỉ định cổng chạy app (Mặc định là 8080)
server.port=8080

# Cấu hình kết nối MySQL
# Đổi 'minibookstore' thành tên database fen đã tạo trong MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/minibookstore?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

# Quan trọng: Lệnh này giúp Spring Boot TỰ ĐỘNG tạo bảng trong MySQL dựa trên Class Entity
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL ra console để dễ debug
spring.jpa.show-sql=true